name: dart_template
description: TODO write 
version: 1.0.0
homepage: https://github.com/rmw-dart/dart_template

environment:
  sdk: '>=2.14.3 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0


